apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "velociraptor.fullname" . }}
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "entry.sh").AsConfig | indent 2 }}
