apiVersion: v1
kind: Service
metadata:
  name: {{ include "velociraptor.fullname" . }}
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: velo-port1
    - port: {{ .Values.service2.port }}
      targetPort: {{ .Values.service2.port }}
      protocol: TCP
      name: velo-port2
    - port: {{ .Values.serviceweb.port }}
      targetPort: {{ .Values.serviceweb.port }}
      protocol: TCP
      name: velo-web
  selector:
    {{- include "velociraptor.selectorLabels" . | nindent 4 }}
