apiVersion: v1
kind: Service
metadata:
  name: {{ include "velociraptor.fullname" . }}
  labels:
    {{- include "velociraptor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port }}
    - port: {{ .Values.service.port2 }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port2 }}
    - port: {{ .Values.service.port3 }}
      targetPort: http
      protocol: TCP
      name: {{ .Values.service.port3 }}
  selector:
    {{- include "velociraptor.selectorLabels" . | nindent 4 }}
