apiVersion: v1
kind: Service
metadata:
  annotations:
    app: velociraptor
  labels:
    app: velociraptor
  name: velociraptor
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8001"
      port: 8001
      targetPort: 8001
    - name: "8889"
      port: 8889
      targetPort: 8889
  selector:
    app: velociraptor