apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: velociraptor
  name: velociraptor-server.config.yaml
  namespace: test
data:
  entry.sh: |-
    #!/bin/bash
    set -e
    CLIENT_DIR="/velociraptor/clients"
    cp /opt/velociraptor/linux/velociraptor . && chmod +x velociraptor
    mkdir -p $CLIENT_DIR/linux && rsync -a /opt/velociraptor/linux/velociraptor /velociraptor/clients/linux/velociraptor_client
    mkdir -p $CLIENT_DIR/mac && rsync -a /opt/velociraptor/mac/velociraptor_client /velociraptor/clients/mac/velociraptor_client
    mkdir -p $CLIENT_DIR/windows && rsync -a /opt/velociraptor/windows/velociraptor_client* /velociraptor/clients/windows/
    echo "mkdir done" && \
    echo "'{"Frontend":{"public_path":"'public'", "hostname":"'Velociraptor'"}, "API":{"bind_address":"'0.0.0.0'"}, "GUI":{"bind_address":"'0.0.0.0'"}, "Monitoring":{"bind_address":"'0.0.0.0'"}, "Logging":{"output_directory":"'./'", "separate_logs_per_component":"'true'"}, "Client":{"server_urls":["'https://velocirpator:'"], "use_self_signed_ssl":"'{{ quote .Values.extraArgs.SELF_SIGNED_CERT }}'"}, "Datastore":{"location":"'{{ .Values.extraArgs.DATASTORE_LOCATION }}'", "filestore_directory":"'{{ .Values.extraArgs.FILESTORE_DIRECTORY }}'"}}'" && \
    ./velociraptor config generate > server.config.yaml --merge '{"Frontend":{"public_path":"'{{ .Values.extraArgs.PUBLIC_PATH }}'", "hostname":"'{{ .Values.extraArgs.VELOX_FRONTEND_HOSTNAME }}'"}, "API":{"bind_address":"'{{ .Values.extraArgs.BIND_ADDRESS }}'"}, "GUI":{"bind_address":"'{{ .Values.extraArgs.BIND_ADDRESS }}'"}, "Monitoring":{"bind_address":"'{{ .Values.extraArgs.BIND_ADDRESS }}'"}, "Logging":{"output_directory":"'{{ .Values.extraArgs.LOG_DIR }}'", "separate_logs_per_component":"'{{ quote .Values.extraArgs.LOG_PER_COMPONENT }}'"}, "Client":{"server_urls":["'{{ .Values.extraArgs.VELOX_SERVER_URL }}'"], "use_self_signed_ssl":"'{{ quote .Values.extraArgs.SELF_SIGNED_CERT }}'"}, "Datastore":{"location":"'{{ .Values.extraArgs.DATASTORE_LOCATION }}'", "filestore_directory":"'{{ .Values.extraArgs.FILESTORE_DIRECTORY }}'"}}' &&\
    echo "merge done" && \
    ./velociraptor --config server.config.yaml user add {{ .Values.extraArgs.VELOX_USER }} {{ .Values.extraArgs.VELOX_PASSWORD }} --role administrator &&\
    echo "added user" && \
    ./velociraptor --config server.config.yaml config client > client.config.yaml &&\
    echo "client config done" && \
    ./velociraptor config repack --exe clients/linux/velociraptor_client client.config.yaml clients/linux/velociraptor_client_repacked &&\
    ./velociraptor config repack --exe clients/mac/velociraptor_client client.config.yaml clients/mac/velociraptor_client_repacked &&\
    ./velociraptor config repack --exe clients/windows/velociraptor_client.exe client.config.yaml clients/windows/velociraptor_client_repacked.exe &&\
    echo "clients repacked" && \
    ./velociraptor --config server.config.yaml frontend -v