apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: velociraptor
  name: velociraptor-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-path
